### ISSUE TITLE
[Question] Is it possible to send notification to different webhook URL based on pipeline?

### ISSUE THREAD

**Issue by Kotsuha** [1and1/go-gchat-notifier-plugin#38]
I'd imagine I may have multiple pipelines for different project. Each project may want to send to different chat.

**Comment by sfuhrm** [comment]
In software, everything is possible ;).
It would actually include reworking the whole settings mechanism which is 60-70% of the code.
I'm not 100% sure how often the settings view HTML is re-rendered, but it would need to be re-rendered for every change of the webhook URL count. 

If re-rendering is not done often enough, it will suck to add more rules since a manual page reload is necessary. So this would need to be checked first.

These API endpoints docs do not tell anything about how often and when the API call is done:

* https://plugin-api.gocd.org/current/notifications/#get-settings-view
* https://plugin-api.gocd.org/current/notifications/#get-plugin-configuration

Feel free to file a PR if you want to implement it. I'll keep this issue open in case you've got more questions.

**Comment by Kotsuha** [comment]
Thank you for keeping this open for me. I do not see myself implementing this within the next two months...
Some people don't like to have an issue idle and open for too long. If you want to close the issue, feel free :)
If I end up implementing this, I can come back whenever and reopen this.

**Comment by sfuhrm** [comment]
Sure, feel free to ask me for hints anytime.
